### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/hackathon-2024#22]
(removed my zoom link)

**Comment by liamhuber** [comment]
Outside of the general assemblies, if you want to talk to me synchronously, check the pyiron room (cf. [the regular meeting discussion](https://github.com/orgs/pyiron/discussions/244) for a zoom link). This way @jan-janssen doesn't have to worry about keeping his laptop open/zoom link live.

**Comment by liamhuber** [comment]
@all I'm in the zoom room
